import Head from 'next/head'
import { getAllPosts } from '../../lib/data';
import { format, parseISO } from 'date-fns'
import { serialize } from 'next-mdx-remote/serialize'
import { MDXRemote } from 'next-mdx-remote'


export default function BlogPage({ frontMatter, source }) {
  return (
    <div className="wrapper">
      <div>
      <Head>
        <title>{frontMatter.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='mb-4'>
        
          <h2 className='text-3xl font-bold '>
            {frontMatter.title}
          </h2>
          
          <div className='text-gray-600 text-xs'>
          {format(parseISO(frontMatter.date), 'd. MMMM uuu')}
          </div>

        </div>

        <div className="whitespace-pre">
          <MDXRemote {...source} />
        </div>

      </main>
    </div>
    </div>
  )
}

export async function getStaticProps(context) {
  const { params } = context
  const allPosts = getAllPosts()
  const { data, content } = allPosts.find(item => item.slug === params.slug)
  const mdxSource = await serialize(content, { scope: data })
  return { 
    props: { 
      frontMatter: data, 
      source: mdxSource 
    } 
  }
}

export async function getStaticPaths() {
    return {
      paths: getAllPosts().map(post => (
        { 
          params: {slug: post.slug}
        })),
      fallback: false
    }
  }
  