import Link from 'next/link'

import Head from 'next/head'
import { blogPosts } from '../lib/data'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>
          My Tailwind & Markdown Blog.
        </h1>
        {blogPosts.map((item) => (
          <div key={item.slug}>
            <div>
              <Link href={`blog/${item.slug}`}>
                <a>{item.title}</a>
              </Link>
            </div>
            <div>{item.date.toString()}</div>
            <div>{item.content}</div>
          </div>
        ))}
      </main>
    </div>
  )
}
